appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c32d1a6d1578b0700305b9e
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: WHhCQIlO0arLTVFp302hUfsItU2F5Yjjt/kIzRY9GA62PpkxMx8iUe7bUAwXG2IQzxmj4WFUt1nn7G+7P7DVIXJ98R2iDmucbnYjSvcCX8nA9kzNKSgM9ABJEDwxPiZgVBuu3fsFW4PCBR0jju/LxniOxvRlBvBew5yrktxFyR4aNvN8lCboudwVO8m8Vn/8yNh34AkWuORG+29pLlwPlCuTITF7Rxt5K33Y+PiKrCY+4mm27doP3hn9bLk2xvhsr4VEw1DRG63H+dxlwlCAwB42wKeuuWaoNEwLXEwbjLL+hegB2OG0HaQJNm5bdp7PddjsdRcCflHpzVU7a/SJjq62Vzhu1ZjEXECSmX9gru7ou2Rpk65YK1KcMfQnWHqqMyPvXXZQdZIBt6XC8hr1o4lTRVTKMeFG07PIkm8bdCqLqNRHg3uIK3AkarvyiM24Ba7PRmJjQHpM8fDUy/M8oFX9V9wujGFuIoyDM7dYWSG5VzTr5jehYd8fwjo1cPvEo+ylQM/Gy5axPqJTE63DBabTGcMeH/eYvyp7s8AF4lYlWK8PkuHszs+rEsxfon4jH+Gt9QZLmXNtXrCX5qAFya6s2CoCbvNfYamB7tsuqig10qwFrrJ4eXC3UwXjsXgf9SXoGDRC1UOhPKHXjZ9nalCo0hp29yJwBYsaXSji9qI=}
